services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_MAPBOX_TOKEN: ${VITE_MAPBOX_TOKEN}
    container_name: alerta-recife-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=https://recifeapi.carldev.online
    restart: unless-stopped

